
$image = /home/khalyl/wallpaper.png
$background = rgba(111318ff)

$image = /home/khalyl/wallpaper.png
$error = rgba(ffb4abff)

$image = /home/khalyl/wallpaper.png
$error_container = rgba(93000aff)

$image = /home/khalyl/wallpaper.png
$inverse_on_surface = rgba(2e3035ff)

$image = /home/khalyl/wallpaper.png
$inverse_primary = rgba(3d5f90ff)

$image = /home/khalyl/wallpaper.png
$inverse_surface = rgba(e1e2e9ff)

$image = /home/khalyl/wallpaper.png
$on_background = rgba(e1e2e9ff)

$image = /home/khalyl/wallpaper.png
$on_error = rgba(690005ff)

$image = /home/khalyl/wallpaper.png
$on_error_container = rgba(ffdad6ff)

$image = /home/khalyl/wallpaper.png
$on_primary = rgba(03305fff)

$image = /home/khalyl/wallpaper.png
$on_primary_container = rgba(d5e3ffff)

$image = /home/khalyl/wallpaper.png
$on_primary_fixed = rgba(001c3bff)

$image = /home/khalyl/wallpaper.png
$on_primary_fixed_variant = rgba(234777ff)

$image = /home/khalyl/wallpaper.png
$on_secondary = rgba(273141ff)

$image = /home/khalyl/wallpaper.png
$on_secondary_container = rgba(d9e3f8ff)

$image = /home/khalyl/wallpaper.png
$on_secondary_fixed = rgba(121c2bff)

$image = /home/khalyl/wallpaper.png
$on_secondary_fixed_variant = rgba(3d4758ff)

$image = /home/khalyl/wallpaper.png
$on_surface = rgba(e1e2e9ff)

$image = /home/khalyl/wallpaper.png
$on_surface_variant = rgba(c4c6cfff)

$image = /home/khalyl/wallpaper.png
$on_tertiary = rgba(3e2845ff)

$image = /home/khalyl/wallpaper.png
$on_tertiary_container = rgba(f8d8ffff)

$image = /home/khalyl/wallpaper.png
$on_tertiary_fixed = rgba(27132fff)

$image = /home/khalyl/wallpaper.png
$on_tertiary_fixed_variant = rgba(553f5dff)

$image = /home/khalyl/wallpaper.png
$outline = rgba(8d9199ff)

$image = /home/khalyl/wallpaper.png
$outline_variant = rgba(43474eff)

$image = /home/khalyl/wallpaper.png
$primary = rgba(a7c8ffff)

$image = /home/khalyl/wallpaper.png
$primary_container = rgba(234777ff)

$image = /home/khalyl/wallpaper.png
$primary_fixed = rgba(d5e3ffff)

$image = /home/khalyl/wallpaper.png
$primary_fixed_dim = rgba(a7c8ffff)

$image = /home/khalyl/wallpaper.png
$scrim = rgba(000000ff)

$image = /home/khalyl/wallpaper.png
$secondary = rgba(bdc7dcff)

$image = /home/khalyl/wallpaper.png
$secondary_container = rgba(3d4758ff)

$image = /home/khalyl/wallpaper.png
$secondary_fixed = rgba(d9e3f8ff)

$image = /home/khalyl/wallpaper.png
$secondary_fixed_dim = rgba(bdc7dcff)

$image = /home/khalyl/wallpaper.png
$shadow = rgba(000000ff)

$image = /home/khalyl/wallpaper.png
$source_color = rgba(3564a2ff)

$image = /home/khalyl/wallpaper.png
$surface = rgba(111318ff)

$image = /home/khalyl/wallpaper.png
$surface_bright = rgba(37393eff)

$image = /home/khalyl/wallpaper.png
$surface_container = rgba(1d2024ff)

$image = /home/khalyl/wallpaper.png
$surface_container_high = rgba(282a2fff)

$image = /home/khalyl/wallpaper.png
$surface_container_highest = rgba(32353aff)

$image = /home/khalyl/wallpaper.png
$surface_container_low = rgba(191c20ff)

$image = /home/khalyl/wallpaper.png
$surface_container_lowest = rgba(0c0e13ff)

$image = /home/khalyl/wallpaper.png
$surface_dim = rgba(111318ff)

$image = /home/khalyl/wallpaper.png
$surface_tint = rgba(a7c8ffff)

$image = /home/khalyl/wallpaper.png
$surface_variant = rgba(43474eff)

$image = /home/khalyl/wallpaper.png
$tertiary = rgba(dbbde2ff)

$image = /home/khalyl/wallpaper.png
$tertiary_container = rgba(553f5dff)

$image = /home/khalyl/wallpaper.png
$tertiary_fixed = rgba(f8d8ffff)

$image = /home/khalyl/wallpaper.png
$tertiary_fixed_dim = rgba(dbbde2ff)

