# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x191112ff
bordercolor = 0xa28b8cff
focuscolor = 0xffb2b8ff
maximizescreencolor = 0xf2b8bcff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xfeba50ff
globalcolor = 0x7c2a37ff
overlaycolor = 0x653b3fff
