exec-once = qs -c noctalia-shell
exec-once = wl-paste --watch cliphist store
# exec-once = mako
exec-once = gamepad
exec-once = wswitch --daemon
# exec-once = awww-daemon
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_MENU_PREFIX QT_QPA_PLATFORMTHEME
exec-once = /usr/lib/pam_kwallet_init
exec-once = nm-applet
exec-once = wlsunset -g 0.8 -t 6000 -T 6500
exec-once = librewolf
exec-once = steam
exec-once = heroic
exec-once = elysia
exec-once = discord
